# Generated by Django 4.2.3 on 2023-07-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'İstifadəçi', 'verbose_name_plural': 'İstifadəçilər'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
    ]
