# Generated by Django 4.2.3 on 2023-08-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id'], 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Messages (0)'},
        ),
    ]
