# Generated by Django 4.2.3 on 2023-08-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
