# Generated by Django 4.2.3 on 2023-08-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_message_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-status', '-id'], 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar (1)'},
        ),
    ]
