# Generated by Django 4.2.3 on 2023-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Əlaqə nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatı',
                'verbose_name_plural': 'Əlaqə məlumatları',
            },
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Loqo')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_image/', verbose_name='Banner şəkli')),
                ('banner_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Banner başlığı')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='Haqqımızda')),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametrlər',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Ölçü')),
            ],
            options={
                'verbose_name': 'Ölçü',
                'verbose_name_plural': 'Ölçülər',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Şəkil')),
                ('title', models.CharField(max_length=512, verbose_name='Başlıq')),
                ('price', models.FloatField(default=0, verbose_name='Qiymət')),
                ('sizes', models.ManyToManyField(blank=True, to='tailor.sizemodel', verbose_name='Ölçülər')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ('-id',),
            },
        ),
    ]
