# Generated by Django 4.2.3 on 2023-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Rəng')),
                ('color_code', models.CharField(max_length=10, verbose_name='Rəng kodu')),
            ],
            options={
                'verbose_name': 'Rəng',
                'verbose_name_plural': 'Rənglər',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(blank=True, to='tailor.colormodel', verbose_name='Rənglər'),
        ),
    ]
