# Generated by Django 4.2.3 on 2023-07-16 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailor', '0002_colormodel_productmodel_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sale_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Endirimli qiymət'),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Əlaqə nömrəsi')),
                ('address', models.TextField(verbose_name='Ünvan')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Qeyd')),
                ('status', models.CharField(choices=[('C', 'Çatdırılıb'), ('CM', 'Çatdırılmayıb')], default='CM', max_length=2, verbose_name='Status')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Miqdar')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderitems', to='tailor.ordermodel', verbose_name='Sifariş')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orderitems', to='tailor.productmodel', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Sifariş edilən',
                'verbose_name_plural': 'Sifarişlər edilənlər',
                'ordering': ('-id',),
            },
        ),
    ]
