# Generated by Django 4.2.3 on 2023-08-07 17:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailor', '0003_productmodel_sale_price_ordermodel_orderitemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=528, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='orderitemmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Sifariş edilən', 'verbose_name_plural': 'Sifariş edilənlər'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Sifarişçi', 'verbose_name_plural': 'Sifarişçilər'},
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rəng'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölçü'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='characteristics',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Xarakteristika'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Qeyd'),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='tailor.productmodel')),
            ],
            options={
                'verbose_name': 'Məhsul şəkli',
                'verbose_name_plural': 'Məhsul şəkilləri',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FavouriteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favourites', to='tailor.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorit',
                'verbose_name_plural': 'Favoritlər',
                'ordering': ('-id',),
            },
        ),
    ]
