# Generated by Django 4.2.3 on 2023-08-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0004_categorymodel_alter_orderitemmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_products', to='tailor.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='color_products', to='tailor.colormodel', verbose_name='Rənglər'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='size_products', to='tailor.sizemodel', verbose_name='Ölçülər'),
        ),
    ]
