# Generated by Django 4.2.3 on 2023-08-11 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tailor', '0005_productmodel_categories_alter_productmodel_colors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Sifarişçi', 'verbose_name_plural': 'Sifarişçilər (1)'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi'),
        ),
    ]
